### ISSUE TITLE
Released version

### ISSUE THREAD

**Issue by peter279k** [heiglandreas/UTCDateTime#8]
Firstly, looking at the [released page](https://github.com/heiglandreas/UTCDateTime/releases), it seems that the released versions doesn't make sense.

I think we can let upcoming released version follow [semver](https://semver.org/) rule.

**Comment by heiglandreas** [comment]
Makes perfect sense to me. The first version followed SemVer in declaring that it is the first pre-release. there is no patch release there, so 0.1. And the second declared that there is a stable API and it therefore is 1.0.0. So absolutely SemVer. And following releases will also follow SemVer...
