### ISSUE TITLE
Drop php-5.x and HHVM supports

### ISSUE THREAD

**Issue by peter279k** [heiglandreas/UTCDateTime#9]
As title, the `php-7.0` version has been released for about three years.

And I think it's time to upgrade this package PHP version requirement to `php-7.0` at least.

Once this issue is accepted, I can do this work :).

**Comment by heiglandreas** [comment]
This has been resolved with #10 and with [release 1.1.0](https://github.com/heiglandreas/UTCDateTime/releases/tag/1.1.0)
